export enum SeriesLBCategoriesTemplateType {
    CONTEST_JOIN = 'CONTEST_JOIN',
    PRIZE_WON = 'PRIZE_WON',
    LOYALTY_POINTS = 'LOYALTY_POINTS',
    LOYALTY_DEPOSIT_POINTS = 'LOYALTY_DEPOSIT_POINTS'
}
