export enum AdminTypeEnums {
  SUPER = 'SUPER',
  SUB = 'SUB'
}

export enum AdminLogKeys {
  // D = DEPOSIT, W = WITHDRAW, P = PROFILE, BD = BANK DETAILS, SA = SUBADMIN, AD = ADMIN DEPOSIT, AW = ADMIN WITHDRAW, PC = PROMOCODE, L = LEAGUE, PB = PRIZE BREAKUP, M = MATCH, ML = MATCHLEAGUE, CR = COMMON RULE, S = SETTINGS, MP= MATCHPLAYER, CF = COMPLAINTS/FEEDBACK, SLB = SERIES LEADERBOARD
  DEPOSIT = 'D',
  WITHDRAW = 'W',
  PROFILE = 'P',
  BANK_DETAILS = 'BD',
  SUBADMIN = 'SA',
  ADMIN_DEPOSIT = 'AD',
  ADMIN_WITHDRAW = 'AW',
  PROMOCODE = 'PC',
  LEAGUE = 'L',
  PRIZE_BREAKUP = 'PB',
  MATCH = 'M',
  MATCHLEAGUE = 'ML',
  COMMON_RULE = 'CR',
  SETTINGS = 'S',
  MATCHPLAYER = 'MP',
  COMPLAINTS_OR_FEEDBACK = 'CF',
  SERIES_LEADERBOARD = 'SLB',
  KYC = 'KYC',
  SUB = 'SUB'
}
